### ISSUE TITLE
TypeError on validation_steps in model.fit_generator

### ISSUE THREAD

**Issue by kihosuh** [petrosgk/Kaggle-Carvana-Image-Masking-Challenge#12]
I keep getting TypeError on validation_step. I looked up on stackoverflow and tried few ones but cannot solve this issue. Has anyone solved this issue?

```
/home/airikiho/anaconda3/envs/py27/lib/python2.7/site-packages/keras/callbacks.py:494: RuntimeWarning: Early stopping requires val_dice_loss available!
  (self.monitor), RuntimeWarning)
Traceback (most recent call last):
  File "train.py", line 174, in <module>
    validation_steps=np.ceil(float(len(ids_valid_split)) / float(batch_size)))
  File "/home/airikiho/anaconda3/envs/py27/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/airikiho/anaconda3/envs/py27/lib/python2.7/site-packages/keras/engine/training.py", line 1939, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/airikiho/anaconda3/envs/py27/lib/python2.7/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/airikiho/anaconda3/envs/py27/lib/python2.7/site-packages/keras/callbacks.py", line 496, in on_epoch_end
    if self.monitor_op(current - self.min_delta, self.best):
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

```

**Comment by petrosgk** [comment]
Fix [here](https://github.com/petrosgk/Kaggle-Carvana-Image-Masking-Challenge/commit/a32ca525f313037db5a14c56bd6987f6173d29c4).
