### ISSUE TITLE
Some problem with opencv reading png file

### ISSUE THREAD

**Issue by ajing** [petrosgk/Kaggle-Carvana-Image-Masking-Challenge#6]
This is a bug about cv2 reading png. I am wondering whether you have experienced something similar.

```
  File "train.py", line 115, in train_generator
    mask = cv2.resize(mask, (input_size, input_size))
cv2.error: /feedstock_root/build_artefacts/opencv_1490907195496/work/opencv-3.2.0/modules/imgproc/src/imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize
```

**Comment by petrosgk** [comment]
Make sure you've placed "train", "train_masks" and "test" folders into the "input" folder or change `cv2.imread` path to point to where the images are.

**Comment by ajing** [comment]
The problem is, even I go the the train_mask directory, and do the following, the error still occurs.

```
>>> import cv2
>>> tmp = cv2.imread("c3dafdb02e7f_08_mask.png", 0)
>>> cv2.resize(tmp, (128, 128))
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /feedstock_root/build_artefacts/opencv_1490907195496/work/opencv-3.2.0/modules/imgproc/src/imgwarp.cpp, line 3492
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: /feedstock_root/build_artefacts/opencv_1490907195496/work/opencv-3.2.0/modules/imgproc/src/imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

```

**Comment by petrosgk** [comment]
Can you do a `tmp.shape` to check if image was read correctly? It should return `(1280, 1918)`.

This is what I get:

```
>>> import cv2
>>> img = cv2.imread('0cdf5b5d0ce1_01_mask.png', 0)
>>> img.shape
(1280, 1918)
>>> img_resized = cv2.resize(img, (128, 128))
>>> img_resized.shape
(128, 128)
```

**Comment by ajing** [comment]
It turns out to be my "mogrify" was somehow not installed correctly. The program just copies the gif file. Now it's working. I have the following warning. Is this OK?

`libpng warning: iCCP: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG`

**Comment by petrosgk** [comment]
Glad you found the issue. The warning is just libpng complaining about the embedded color profile but it doesn't cause any problems. If you want to get rid of the warning you can strip the metadata from the images like this:

```
apt-get install exiftool
exiftool -overwrite_original -all= *
```

**Comment by ghost** [comment]
I think I am having a similar issue but my morgify works properly and I have png files but still, I have facing this issue please any solution?


Epoch 1/100
Traceback (most recent call last):
  File "C:/Users/Shubham Shah/Documents/GitHub/Kaggle-Carvana-Image-Masking-Challenge/train.py", line 158, in <module>
    validation_steps=np.ceil(float(len(ids_valid_split)) / float(batch_size)))
  File "C:\Users\Shubham Shah\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Shubham Shah\Anaconda3\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Shubham Shah\Anaconda3\lib\site-packages\keras\engine\training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\Shubham Shah\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "C:\Users\Shubham Shah\Anaconda3\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Shubham Shah\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "C:\Users\Shubham Shah\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\Users\Shubham Shah\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Shubham Shah\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "C:/Users/Shubham Shah/Documents/GitHub/Kaggle-Carvana-Image-Masking-Challenge/train.py", line 97, in train_generator
    img = cv2.resize(img, (input_size, input_size))
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'


Process finished with exit code 1
